baseurl = "http://markstruzinski.com"
languageCode = "en-us"
title = "Mark Struzinski"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = "ski081"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hyde"

[params]
    description = "Thoughts on Technology and Software Development."
    copyright = ""

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

[[menu.main]]
    url = "/contact/"
    name = "Contact"
    weight = 4


[social]
    twitter   = "https://twitter.com/ski081"
    linkedin  = "www.linkedin.com/in/mark-struzinski"
    github    = "https://github.com/ski081"
